// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AgentBridgeServer/AgentBridge.proto

#include "AgentBridgeServer/AgentBridge.pb.h"
#include "AgentBridgeServer/AgentBridge.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace AgentBridgeServer {

static const char* AgentBridgeService_method_names[] = {
  "/AgentBridgeServer.AgentBridgeService/ListWorlds",
  "/AgentBridgeServer.AgentBridgeService/SetTargetWorld",
  "/AgentBridgeServer.AgentBridgeService/QueryActors",
  "/AgentBridgeServer.AgentBridgeService/GetActor",
  "/AgentBridgeServer.AgentBridgeService/SpawnActor",
  "/AgentBridgeServer.AgentBridgeService/DeleteActor",
  "/AgentBridgeServer.AgentBridgeService/SetActorTransform",
  "/AgentBridgeServer.AgentBridgeService/SetActorProperties",
  "/AgentBridgeServer.AgentBridgeService/GetPropertyPath",
  "/AgentBridgeServer.AgentBridgeService/SetPropertyPath",
  "/AgentBridgeServer.AgentBridgeService/CallFunction",
  "/AgentBridgeServer.AgentBridgeService/FindClass",
  "/AgentBridgeServer.AgentBridgeService/GetClassSchema",
  "/AgentBridgeServer.AgentBridgeService/ListClasses",
};

std::unique_ptr< AgentBridgeService::Stub> AgentBridgeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AgentBridgeService::Stub> stub(new AgentBridgeService::Stub(channel, options));
  return stub;
}

AgentBridgeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListWorlds_(AgentBridgeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTargetWorld_(AgentBridgeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryActors_(AgentBridgeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetActor_(AgentBridgeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SpawnActor_(AgentBridgeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteActor_(AgentBridgeService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetActorTransform_(AgentBridgeService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetActorProperties_(AgentBridgeService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPropertyPath_(AgentBridgeService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPropertyPath_(AgentBridgeService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CallFunction_(AgentBridgeService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindClass_(AgentBridgeService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetClassSchema_(AgentBridgeService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListClasses_(AgentBridgeService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AgentBridgeService::Stub::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::AgentBridgeServer::ListWorldsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListWorlds_, context, request, response);
}

void AgentBridgeService::Stub::async::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListWorlds_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListWorlds_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListWorldsResponse>* AgentBridgeService::Stub::PrepareAsyncListWorldsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::ListWorldsResponse, ::AgentBridgeServer::ListWorldsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListWorlds_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListWorldsResponse>* AgentBridgeService::Stub::AsyncListWorldsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListWorldsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTargetWorld_, context, request, response);
}

void AgentBridgeService::Stub::async::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetWorld_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetWorld_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetTargetWorldRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetTargetWorldRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTargetWorld_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetTargetWorldRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTargetWorldRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::AgentBridgeServer::QueryActorsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryActors_, context, request, response);
}

void AgentBridgeService::Stub::async::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryActors_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryActors_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryActorsResponse>* AgentBridgeService::Stub::PrepareAsyncQueryActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::QueryActorsResponse, ::AgentBridgeServer::QueryActorsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryActors_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryActorsResponse>* AgentBridgeService::Stub::AsyncQueryActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryActorsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::AgentBridgeServer::GetActorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetActor_, context, request, response);
}

void AgentBridgeService::Stub::async::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorResponse>* AgentBridgeService::Stub::PrepareAsyncGetActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetActorResponse, ::AgentBridgeServer::GetActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorResponse>* AgentBridgeService::Stub::AsyncGetActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::AgentBridgeServer::SpawnActorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SpawnActor_, context, request, response);
}

void AgentBridgeService::Stub::async::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SpawnActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SpawnActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SpawnActorResponse>* AgentBridgeService::Stub::PrepareAsyncSpawnActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::SpawnActorResponse, ::AgentBridgeServer::SpawnActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SpawnActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SpawnActorResponse>* AgentBridgeService::Stub::AsyncSpawnActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSpawnActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteActor_, context, request, response);
}

void AgentBridgeService::Stub::async::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncDeleteActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::DeleteActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncDeleteActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetActorTransform_, context, request, response);
}

void AgentBridgeService::Stub::async::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorTransform_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorTransform_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetActorTransformRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetActorTransformRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetActorTransform_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetActorTransformRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetActorTransformRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::AgentBridgeServer::SetActorPropertiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetActorProperties_, context, request, response);
}

void AgentBridgeService::Stub::async::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorProperties_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorProperties_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SetActorPropertiesResponse>* AgentBridgeService::Stub::PrepareAsyncSetActorPropertiesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::SetActorPropertiesResponse, ::AgentBridgeServer::SetActorPropertiesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetActorProperties_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SetActorPropertiesResponse>* AgentBridgeService::Stub::AsyncSetActorPropertiesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetActorPropertiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::AgentBridgeServer::GetPropertyPathResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPropertyPath_, context, request, response);
}

void AgentBridgeService::Stub::async::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPath_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetPropertyPathResponse>* AgentBridgeService::Stub::PrepareAsyncGetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetPropertyPathResponse, ::AgentBridgeServer::GetPropertyPathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPropertyPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetPropertyPathResponse>* AgentBridgeService::Stub::AsyncGetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPropertyPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPropertyPath_, context, request, response);
}

void AgentBridgeService::Stub::async::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPath_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetPropertyPathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPropertyPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPropertyPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::AgentBridgeServer::CallFunctionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallFunction_, context, request, response);
}

void AgentBridgeService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::CallFunctionResponse>* AgentBridgeService::Stub::PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::CallFunctionResponse, ::AgentBridgeServer::CallFunctionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallFunction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::CallFunctionResponse>* AgentBridgeService::Stub::AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallFunctionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::AgentBridgeServer::FindClassResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindClass_, context, request, response);
}

void AgentBridgeService::Stub::async::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindClass_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindClass_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::FindClassResponse>* AgentBridgeService::Stub::PrepareAsyncFindClassRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::FindClassResponse, ::AgentBridgeServer::FindClassRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindClass_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::FindClassResponse>* AgentBridgeService::Stub::AsyncFindClassRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindClassRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::AgentBridgeServer::GetClassSchemaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClassSchema_, context, request, response);
}

void AgentBridgeService::Stub::async::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClassSchema_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClassSchema_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetClassSchemaResponse>* AgentBridgeService::Stub::PrepareAsyncGetClassSchemaRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetClassSchemaResponse, ::AgentBridgeServer::GetClassSchemaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClassSchema_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetClassSchemaResponse>* AgentBridgeService::Stub::AsyncGetClassSchemaRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClassSchemaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::AgentBridgeServer::ListClassesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListClasses_, context, request, response);
}

void AgentBridgeService::Stub::async::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListClasses_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListClasses_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListClassesResponse>* AgentBridgeService::Stub::PrepareAsyncListClassesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::ListClassesResponse, ::AgentBridgeServer::ListClassesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListClasses_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListClassesResponse>* AgentBridgeService::Stub::AsyncListClassesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListClassesRaw(context, request, cq);
  result->StartCall();
  return result;
}

AgentBridgeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::ListWorldsRequest* req,
             ::AgentBridgeServer::ListWorldsResponse* resp) {
               return service->ListWorlds(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetTargetWorldRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetTargetWorld(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::QueryActorsRequest* req,
             ::AgentBridgeServer::QueryActorsResponse* resp) {
               return service->QueryActors(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetActorRequest* req,
             ::AgentBridgeServer::GetActorResponse* resp) {
               return service->GetActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SpawnActorRequest* req,
             ::AgentBridgeServer::SpawnActorResponse* resp) {
               return service->SpawnActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::DeleteActorRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->DeleteActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetActorTransformRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetActorTransform(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetActorPropertiesRequest* req,
             ::AgentBridgeServer::SetActorPropertiesResponse* resp) {
               return service->SetActorProperties(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetPropertyPathRequest* req,
             ::AgentBridgeServer::GetPropertyPathResponse* resp) {
               return service->GetPropertyPath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetPropertyPathRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetPropertyPath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::CallFunctionRequest* req,
             ::AgentBridgeServer::CallFunctionResponse* resp) {
               return service->CallFunction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::FindClassRequest* req,
             ::AgentBridgeServer::FindClassResponse* resp) {
               return service->FindClass(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetClassSchemaRequest* req,
             ::AgentBridgeServer::GetClassSchemaResponse* resp) {
               return service->GetClassSchema(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::ListClassesRequest* req,
             ::AgentBridgeServer::ListClassesResponse* resp) {
               return service->ListClasses(ctx, req, resp);
             }, this)));
}

AgentBridgeService::Service::~Service() {
}

::grpc::Status AgentBridgeService::Service::ListWorlds(::grpc::ServerContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetTargetWorld(::grpc::ServerContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::QueryActors(::grpc::ServerContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetActor(::grpc::ServerContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SpawnActor(::grpc::ServerContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::DeleteActor(::grpc::ServerContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetActorTransform(::grpc::ServerContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetActorProperties(::grpc::ServerContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetPropertyPath(::grpc::ServerContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetPropertyPath(::grpc::ServerContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::CallFunction(::grpc::ServerContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::FindClass(::grpc::ServerContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetClassSchema(::grpc::ServerContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::ListClasses(::grpc::ServerContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace AgentBridgeServer

