// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: AgentBridgeServer/AgentBridge.proto

#include "AgentBridgeServer/AgentBridge.pb.h"
#include "AgentBridgeServer/AgentBridge.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace AgentBridgeServer {

static const char* AgentBridgeService_method_names[] = {
  "/AgentBridgeServer.AgentBridgeService/ListWorlds",
  "/AgentBridgeServer.AgentBridgeService/SetTargetWorld",
  "/AgentBridgeServer.AgentBridgeService/QueryActors",
  "/AgentBridgeServer.AgentBridgeService/GetActor",
  "/AgentBridgeServer.AgentBridgeService/SpawnActor",
  "/AgentBridgeServer.AgentBridgeService/DeleteActor",
  "/AgentBridgeServer.AgentBridgeService/SetActorTransform",
  "/AgentBridgeServer.AgentBridgeService/SetActorProperties",
  "/AgentBridgeServer.AgentBridgeService/GetPropertyPath",
  "/AgentBridgeServer.AgentBridgeService/SetPropertyPath",
  "/AgentBridgeServer.AgentBridgeService/CallFunction",
  "/AgentBridgeServer.AgentBridgeService/FindClass",
  "/AgentBridgeServer.AgentBridgeService/GetClassSchema",
  "/AgentBridgeServer.AgentBridgeService/ListClasses",
  "/AgentBridgeServer.AgentBridgeService/IsWorldPartitioned",
  "/AgentBridgeServer.AgentBridgeService/QueryAllActors",
  "/AgentBridgeServer.AgentBridgeService/GetStreamingState",
  "/AgentBridgeServer.AgentBridgeService/QueryLandscape",
  "/AgentBridgeServer.AgentBridgeService/GetDataLayers",
  "/AgentBridgeServer.AgentBridgeService/GetActorsInDataLayer",
  "/AgentBridgeServer.AgentBridgeService/ExecuteConsoleCommand",
};

std::unique_ptr< AgentBridgeService::Stub> AgentBridgeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AgentBridgeService::Stub> stub(new AgentBridgeService::Stub(channel, options));
  return stub;
}

AgentBridgeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListWorlds_(AgentBridgeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetTargetWorld_(AgentBridgeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryActors_(AgentBridgeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetActor_(AgentBridgeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SpawnActor_(AgentBridgeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_DeleteActor_(AgentBridgeService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetActorTransform_(AgentBridgeService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetActorProperties_(AgentBridgeService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetPropertyPath_(AgentBridgeService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetPropertyPath_(AgentBridgeService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CallFunction_(AgentBridgeService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FindClass_(AgentBridgeService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetClassSchema_(AgentBridgeService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListClasses_(AgentBridgeService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_IsWorldPartitioned_(AgentBridgeService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryAllActors_(AgentBridgeService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetStreamingState_(AgentBridgeService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryLandscape_(AgentBridgeService_method_names[17], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetDataLayers_(AgentBridgeService_method_names[18], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetActorsInDataLayer_(AgentBridgeService_method_names[19], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ExecuteConsoleCommand_(AgentBridgeService_method_names[20], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AgentBridgeService::Stub::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::AgentBridgeServer::ListWorldsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListWorlds_, context, request, response);
}

void AgentBridgeService::Stub::async::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListWorlds_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::ListWorlds(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListWorlds_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListWorldsResponse>* AgentBridgeService::Stub::PrepareAsyncListWorldsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::ListWorldsResponse, ::AgentBridgeServer::ListWorldsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListWorlds_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListWorldsResponse>* AgentBridgeService::Stub::AsyncListWorldsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListWorldsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListWorldsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetTargetWorld_, context, request, response);
}

void AgentBridgeService::Stub::async::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetWorld_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetTargetWorld(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetTargetWorld_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetTargetWorldRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetTargetWorldRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetTargetWorld_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetTargetWorldRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetTargetWorldRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetTargetWorldRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::AgentBridgeServer::QueryActorsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryActors_, context, request, response);
}

void AgentBridgeService::Stub::async::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryActors_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::QueryActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryActors_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryActorsResponse>* AgentBridgeService::Stub::PrepareAsyncQueryActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::QueryActorsResponse, ::AgentBridgeServer::QueryActorsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryActors_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryActorsResponse>* AgentBridgeService::Stub::AsyncQueryActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryActorsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryActorsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::AgentBridgeServer::GetActorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetActor_, context, request, response);
}

void AgentBridgeService::Stub::async::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetActor(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorResponse>* AgentBridgeService::Stub::PrepareAsyncGetActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetActorResponse, ::AgentBridgeServer::GetActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorResponse>* AgentBridgeService::Stub::AsyncGetActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::AgentBridgeServer::SpawnActorResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SpawnActor_, context, request, response);
}

void AgentBridgeService::Stub::async::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SpawnActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SpawnActor(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SpawnActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SpawnActorResponse>* AgentBridgeService::Stub::PrepareAsyncSpawnActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::SpawnActorResponse, ::AgentBridgeServer::SpawnActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SpawnActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SpawnActorResponse>* AgentBridgeService::Stub::AsyncSpawnActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SpawnActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSpawnActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_DeleteActor_, context, request, response);
}

void AgentBridgeService::Stub::async::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteActor_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::DeleteActor(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_DeleteActor_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncDeleteActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::DeleteActorRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_DeleteActor_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncDeleteActorRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::DeleteActorRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncDeleteActorRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetActorTransform_, context, request, response);
}

void AgentBridgeService::Stub::async::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorTransform_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetActorTransform(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorTransform_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetActorTransformRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetActorTransformRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetActorTransform_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetActorTransformRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorTransformRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetActorTransformRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::AgentBridgeServer::SetActorPropertiesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetActorProperties_, context, request, response);
}

void AgentBridgeService::Stub::async::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorProperties_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetActorProperties(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetActorProperties_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SetActorPropertiesResponse>* AgentBridgeService::Stub::PrepareAsyncSetActorPropertiesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::SetActorPropertiesResponse, ::AgentBridgeServer::SetActorPropertiesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetActorProperties_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::SetActorPropertiesResponse>* AgentBridgeService::Stub::AsyncSetActorPropertiesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetActorPropertiesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::AgentBridgeServer::GetPropertyPathResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetPropertyPath_, context, request, response);
}

void AgentBridgeService::Stub::async::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPath_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetPropertyPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetPropertyPathResponse>* AgentBridgeService::Stub::PrepareAsyncGetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetPropertyPathResponse, ::AgentBridgeServer::GetPropertyPathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetPropertyPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetPropertyPathResponse>* AgentBridgeService::Stub::AsyncGetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetPropertyPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::TempoScripting::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetPropertyPath_, context, request, response);
}

void AgentBridgeService::Stub::async::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPath_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::SetPropertyPath(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetPropertyPath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::PrepareAsyncSetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::TempoScripting::Empty, ::AgentBridgeServer::SetPropertyPathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetPropertyPath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::TempoScripting::Empty>* AgentBridgeService::Stub::AsyncSetPropertyPathRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::SetPropertyPathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetPropertyPathRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::AgentBridgeServer::CallFunctionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallFunction_, context, request, response);
}

void AgentBridgeService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::CallFunction(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallFunction_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::CallFunctionResponse>* AgentBridgeService::Stub::PrepareAsyncCallFunctionRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::CallFunctionResponse, ::AgentBridgeServer::CallFunctionRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallFunction_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::CallFunctionResponse>* AgentBridgeService::Stub::AsyncCallFunctionRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::CallFunctionRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallFunctionRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::AgentBridgeServer::FindClassResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FindClass_, context, request, response);
}

void AgentBridgeService::Stub::async::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindClass_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::FindClass(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FindClass_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::FindClassResponse>* AgentBridgeService::Stub::PrepareAsyncFindClassRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::FindClassResponse, ::AgentBridgeServer::FindClassRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FindClass_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::FindClassResponse>* AgentBridgeService::Stub::AsyncFindClassRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::FindClassRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFindClassRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::AgentBridgeServer::GetClassSchemaResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetClassSchema_, context, request, response);
}

void AgentBridgeService::Stub::async::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClassSchema_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetClassSchema(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetClassSchema_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetClassSchemaResponse>* AgentBridgeService::Stub::PrepareAsyncGetClassSchemaRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetClassSchemaResponse, ::AgentBridgeServer::GetClassSchemaRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetClassSchema_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetClassSchemaResponse>* AgentBridgeService::Stub::AsyncGetClassSchemaRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetClassSchemaRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetClassSchemaRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::AgentBridgeServer::ListClassesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListClasses_, context, request, response);
}

void AgentBridgeService::Stub::async::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListClasses_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::ListClasses(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListClasses_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListClassesResponse>* AgentBridgeService::Stub::PrepareAsyncListClassesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::ListClassesResponse, ::AgentBridgeServer::ListClassesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListClasses_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ListClassesResponse>* AgentBridgeService::Stub::AsyncListClassesRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ListClassesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListClassesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::IsWorldPartitioned(::grpc::ClientContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest& request, ::AgentBridgeServer::IsWorldPartitionedResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::IsWorldPartitionedRequest, ::AgentBridgeServer::IsWorldPartitionedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_IsWorldPartitioned_, context, request, response);
}

void AgentBridgeService::Stub::async::IsWorldPartitioned(::grpc::ClientContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest* request, ::AgentBridgeServer::IsWorldPartitionedResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::IsWorldPartitionedRequest, ::AgentBridgeServer::IsWorldPartitionedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsWorldPartitioned_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::IsWorldPartitioned(::grpc::ClientContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest* request, ::AgentBridgeServer::IsWorldPartitionedResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_IsWorldPartitioned_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::IsWorldPartitionedResponse>* AgentBridgeService::Stub::PrepareAsyncIsWorldPartitionedRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::IsWorldPartitionedResponse, ::AgentBridgeServer::IsWorldPartitionedRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_IsWorldPartitioned_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::IsWorldPartitionedResponse>* AgentBridgeService::Stub::AsyncIsWorldPartitionedRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncIsWorldPartitionedRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::QueryAllActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryAllActorsRequest& request, ::AgentBridgeServer::QueryAllActorsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::QueryAllActorsRequest, ::AgentBridgeServer::QueryAllActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryAllActors_, context, request, response);
}

void AgentBridgeService::Stub::async::QueryAllActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryAllActorsRequest* request, ::AgentBridgeServer::QueryAllActorsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::QueryAllActorsRequest, ::AgentBridgeServer::QueryAllActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryAllActors_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::QueryAllActors(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryAllActorsRequest* request, ::AgentBridgeServer::QueryAllActorsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryAllActors_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryAllActorsResponse>* AgentBridgeService::Stub::PrepareAsyncQueryAllActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryAllActorsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::QueryAllActorsResponse, ::AgentBridgeServer::QueryAllActorsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryAllActors_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryAllActorsResponse>* AgentBridgeService::Stub::AsyncQueryAllActorsRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryAllActorsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryAllActorsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetStreamingState(::grpc::ClientContext* context, const ::AgentBridgeServer::GetStreamingStateRequest& request, ::AgentBridgeServer::GetStreamingStateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetStreamingStateRequest, ::AgentBridgeServer::GetStreamingStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetStreamingState_, context, request, response);
}

void AgentBridgeService::Stub::async::GetStreamingState(::grpc::ClientContext* context, const ::AgentBridgeServer::GetStreamingStateRequest* request, ::AgentBridgeServer::GetStreamingStateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetStreamingStateRequest, ::AgentBridgeServer::GetStreamingStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamingState_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetStreamingState(::grpc::ClientContext* context, const ::AgentBridgeServer::GetStreamingStateRequest* request, ::AgentBridgeServer::GetStreamingStateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetStreamingState_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetStreamingStateResponse>* AgentBridgeService::Stub::PrepareAsyncGetStreamingStateRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetStreamingStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetStreamingStateResponse, ::AgentBridgeServer::GetStreamingStateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetStreamingState_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetStreamingStateResponse>* AgentBridgeService::Stub::AsyncGetStreamingStateRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetStreamingStateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetStreamingStateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::QueryLandscape(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryLandscapeRequest& request, ::AgentBridgeServer::QueryLandscapeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::QueryLandscapeRequest, ::AgentBridgeServer::QueryLandscapeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryLandscape_, context, request, response);
}

void AgentBridgeService::Stub::async::QueryLandscape(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryLandscapeRequest* request, ::AgentBridgeServer::QueryLandscapeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::QueryLandscapeRequest, ::AgentBridgeServer::QueryLandscapeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryLandscape_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::QueryLandscape(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryLandscapeRequest* request, ::AgentBridgeServer::QueryLandscapeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryLandscape_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryLandscapeResponse>* AgentBridgeService::Stub::PrepareAsyncQueryLandscapeRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryLandscapeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::QueryLandscapeResponse, ::AgentBridgeServer::QueryLandscapeRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryLandscape_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::QueryLandscapeResponse>* AgentBridgeService::Stub::AsyncQueryLandscapeRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::QueryLandscapeRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryLandscapeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetDataLayers(::grpc::ClientContext* context, const ::AgentBridgeServer::GetDataLayersRequest& request, ::AgentBridgeServer::GetDataLayersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetDataLayersRequest, ::AgentBridgeServer::GetDataLayersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetDataLayers_, context, request, response);
}

void AgentBridgeService::Stub::async::GetDataLayers(::grpc::ClientContext* context, const ::AgentBridgeServer::GetDataLayersRequest* request, ::AgentBridgeServer::GetDataLayersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetDataLayersRequest, ::AgentBridgeServer::GetDataLayersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDataLayers_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetDataLayers(::grpc::ClientContext* context, const ::AgentBridgeServer::GetDataLayersRequest* request, ::AgentBridgeServer::GetDataLayersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetDataLayers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetDataLayersResponse>* AgentBridgeService::Stub::PrepareAsyncGetDataLayersRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetDataLayersRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetDataLayersResponse, ::AgentBridgeServer::GetDataLayersRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetDataLayers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetDataLayersResponse>* AgentBridgeService::Stub::AsyncGetDataLayersRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetDataLayersRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetDataLayersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::GetActorsInDataLayer(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest& request, ::AgentBridgeServer::GetActorsInDataLayerResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::GetActorsInDataLayerRequest, ::AgentBridgeServer::GetActorsInDataLayerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetActorsInDataLayer_, context, request, response);
}

void AgentBridgeService::Stub::async::GetActorsInDataLayer(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest* request, ::AgentBridgeServer::GetActorsInDataLayerResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::GetActorsInDataLayerRequest, ::AgentBridgeServer::GetActorsInDataLayerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActorsInDataLayer_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::GetActorsInDataLayer(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest* request, ::AgentBridgeServer::GetActorsInDataLayerResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetActorsInDataLayer_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorsInDataLayerResponse>* AgentBridgeService::Stub::PrepareAsyncGetActorsInDataLayerRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::GetActorsInDataLayerResponse, ::AgentBridgeServer::GetActorsInDataLayerRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetActorsInDataLayer_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::GetActorsInDataLayerResponse>* AgentBridgeService::Stub::AsyncGetActorsInDataLayerRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetActorsInDataLayerRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status AgentBridgeService::Stub::ExecuteConsoleCommand(::grpc::ClientContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest& request, ::AgentBridgeServer::ExecuteConsoleCommandResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::AgentBridgeServer::ExecuteConsoleCommandRequest, ::AgentBridgeServer::ExecuteConsoleCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteConsoleCommand_, context, request, response);
}

void AgentBridgeService::Stub::async::ExecuteConsoleCommand(::grpc::ClientContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest* request, ::AgentBridgeServer::ExecuteConsoleCommandResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::AgentBridgeServer::ExecuteConsoleCommandRequest, ::AgentBridgeServer::ExecuteConsoleCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteConsoleCommand_, context, request, response, std::move(f));
}

void AgentBridgeService::Stub::async::ExecuteConsoleCommand(::grpc::ClientContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest* request, ::AgentBridgeServer::ExecuteConsoleCommandResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteConsoleCommand_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ExecuteConsoleCommandResponse>* AgentBridgeService::Stub::PrepareAsyncExecuteConsoleCommandRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::AgentBridgeServer::ExecuteConsoleCommandResponse, ::AgentBridgeServer::ExecuteConsoleCommandRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteConsoleCommand_, context, request);
}

::grpc::ClientAsyncResponseReader< ::AgentBridgeServer::ExecuteConsoleCommandResponse>* AgentBridgeService::Stub::AsyncExecuteConsoleCommandRaw(::grpc::ClientContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteConsoleCommandRaw(context, request, cq);
  result->StartCall();
  return result;
}

AgentBridgeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::ListWorldsRequest, ::AgentBridgeServer::ListWorldsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::ListWorldsRequest* req,
             ::AgentBridgeServer::ListWorldsResponse* resp) {
               return service->ListWorlds(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetTargetWorldRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetTargetWorldRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetTargetWorld(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::QueryActorsRequest, ::AgentBridgeServer::QueryActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::QueryActorsRequest* req,
             ::AgentBridgeServer::QueryActorsResponse* resp) {
               return service->QueryActors(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetActorRequest, ::AgentBridgeServer::GetActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetActorRequest* req,
             ::AgentBridgeServer::GetActorResponse* resp) {
               return service->GetActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SpawnActorRequest, ::AgentBridgeServer::SpawnActorResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SpawnActorRequest* req,
             ::AgentBridgeServer::SpawnActorResponse* resp) {
               return service->SpawnActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::DeleteActorRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::DeleteActorRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->DeleteActor(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetActorTransformRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetActorTransformRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetActorTransform(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetActorPropertiesRequest, ::AgentBridgeServer::SetActorPropertiesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetActorPropertiesRequest* req,
             ::AgentBridgeServer::SetActorPropertiesResponse* resp) {
               return service->SetActorProperties(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetPropertyPathRequest, ::AgentBridgeServer::GetPropertyPathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetPropertyPathRequest* req,
             ::AgentBridgeServer::GetPropertyPathResponse* resp) {
               return service->GetPropertyPath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::SetPropertyPathRequest, ::TempoScripting::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::SetPropertyPathRequest* req,
             ::TempoScripting::Empty* resp) {
               return service->SetPropertyPath(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::CallFunctionRequest, ::AgentBridgeServer::CallFunctionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::CallFunctionRequest* req,
             ::AgentBridgeServer::CallFunctionResponse* resp) {
               return service->CallFunction(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::FindClassRequest, ::AgentBridgeServer::FindClassResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::FindClassRequest* req,
             ::AgentBridgeServer::FindClassResponse* resp) {
               return service->FindClass(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetClassSchemaRequest, ::AgentBridgeServer::GetClassSchemaResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetClassSchemaRequest* req,
             ::AgentBridgeServer::GetClassSchemaResponse* resp) {
               return service->GetClassSchema(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::ListClassesRequest, ::AgentBridgeServer::ListClassesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::ListClassesRequest* req,
             ::AgentBridgeServer::ListClassesResponse* resp) {
               return service->ListClasses(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::IsWorldPartitionedRequest, ::AgentBridgeServer::IsWorldPartitionedResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::IsWorldPartitionedRequest* req,
             ::AgentBridgeServer::IsWorldPartitionedResponse* resp) {
               return service->IsWorldPartitioned(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::QueryAllActorsRequest, ::AgentBridgeServer::QueryAllActorsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::QueryAllActorsRequest* req,
             ::AgentBridgeServer::QueryAllActorsResponse* resp) {
               return service->QueryAllActors(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetStreamingStateRequest, ::AgentBridgeServer::GetStreamingStateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetStreamingStateRequest* req,
             ::AgentBridgeServer::GetStreamingStateResponse* resp) {
               return service->GetStreamingState(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[17],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::QueryLandscapeRequest, ::AgentBridgeServer::QueryLandscapeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::QueryLandscapeRequest* req,
             ::AgentBridgeServer::QueryLandscapeResponse* resp) {
               return service->QueryLandscape(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[18],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetDataLayersRequest, ::AgentBridgeServer::GetDataLayersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetDataLayersRequest* req,
             ::AgentBridgeServer::GetDataLayersResponse* resp) {
               return service->GetDataLayers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[19],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::GetActorsInDataLayerRequest, ::AgentBridgeServer::GetActorsInDataLayerResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::GetActorsInDataLayerRequest* req,
             ::AgentBridgeServer::GetActorsInDataLayerResponse* resp) {
               return service->GetActorsInDataLayer(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AgentBridgeService_method_names[20],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AgentBridgeService::Service, ::AgentBridgeServer::ExecuteConsoleCommandRequest, ::AgentBridgeServer::ExecuteConsoleCommandResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AgentBridgeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::AgentBridgeServer::ExecuteConsoleCommandRequest* req,
             ::AgentBridgeServer::ExecuteConsoleCommandResponse* resp) {
               return service->ExecuteConsoleCommand(ctx, req, resp);
             }, this)));
}

AgentBridgeService::Service::~Service() {
}

::grpc::Status AgentBridgeService::Service::ListWorlds(::grpc::ServerContext* context, const ::AgentBridgeServer::ListWorldsRequest* request, ::AgentBridgeServer::ListWorldsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetTargetWorld(::grpc::ServerContext* context, const ::AgentBridgeServer::SetTargetWorldRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::QueryActors(::grpc::ServerContext* context, const ::AgentBridgeServer::QueryActorsRequest* request, ::AgentBridgeServer::QueryActorsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetActor(::grpc::ServerContext* context, const ::AgentBridgeServer::GetActorRequest* request, ::AgentBridgeServer::GetActorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SpawnActor(::grpc::ServerContext* context, const ::AgentBridgeServer::SpawnActorRequest* request, ::AgentBridgeServer::SpawnActorResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::DeleteActor(::grpc::ServerContext* context, const ::AgentBridgeServer::DeleteActorRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetActorTransform(::grpc::ServerContext* context, const ::AgentBridgeServer::SetActorTransformRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetActorProperties(::grpc::ServerContext* context, const ::AgentBridgeServer::SetActorPropertiesRequest* request, ::AgentBridgeServer::SetActorPropertiesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetPropertyPath(::grpc::ServerContext* context, const ::AgentBridgeServer::GetPropertyPathRequest* request, ::AgentBridgeServer::GetPropertyPathResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::SetPropertyPath(::grpc::ServerContext* context, const ::AgentBridgeServer::SetPropertyPathRequest* request, ::TempoScripting::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::CallFunction(::grpc::ServerContext* context, const ::AgentBridgeServer::CallFunctionRequest* request, ::AgentBridgeServer::CallFunctionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::FindClass(::grpc::ServerContext* context, const ::AgentBridgeServer::FindClassRequest* request, ::AgentBridgeServer::FindClassResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetClassSchema(::grpc::ServerContext* context, const ::AgentBridgeServer::GetClassSchemaRequest* request, ::AgentBridgeServer::GetClassSchemaResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::ListClasses(::grpc::ServerContext* context, const ::AgentBridgeServer::ListClassesRequest* request, ::AgentBridgeServer::ListClassesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::IsWorldPartitioned(::grpc::ServerContext* context, const ::AgentBridgeServer::IsWorldPartitionedRequest* request, ::AgentBridgeServer::IsWorldPartitionedResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::QueryAllActors(::grpc::ServerContext* context, const ::AgentBridgeServer::QueryAllActorsRequest* request, ::AgentBridgeServer::QueryAllActorsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetStreamingState(::grpc::ServerContext* context, const ::AgentBridgeServer::GetStreamingStateRequest* request, ::AgentBridgeServer::GetStreamingStateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::QueryLandscape(::grpc::ServerContext* context, const ::AgentBridgeServer::QueryLandscapeRequest* request, ::AgentBridgeServer::QueryLandscapeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetDataLayers(::grpc::ServerContext* context, const ::AgentBridgeServer::GetDataLayersRequest* request, ::AgentBridgeServer::GetDataLayersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::GetActorsInDataLayer(::grpc::ServerContext* context, const ::AgentBridgeServer::GetActorsInDataLayerRequest* request, ::AgentBridgeServer::GetActorsInDataLayerResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status AgentBridgeService::Service::ExecuteConsoleCommand(::grpc::ServerContext* context, const ::AgentBridgeServer::ExecuteConsoleCommandRequest* request, ::AgentBridgeServer::ExecuteConsoleCommandResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace AgentBridgeServer

